import os
import sqlite3
import calendar
from datetime import date, datetime, timedelta
from pathlib import Path

from flask import Flask, flash, g, redirect, render_template, request, url_for

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None


BASE_DIR = Path(__file__).resolve().parent
DATABASE = BASE_DIR / "attendance.db"
DATABASE_URL = os.environ.get("DATABASE_URL")

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev-key-change-this")


def get_db():
    if "db" not in g:
        g.db = Database()
    return g.db


class Database:
    def __init__(self):
        self.is_postgres = bool(DATABASE_URL)
        if self.is_postgres:
            if psycopg is None:
                raise RuntimeError("DATABASE_URL is set, but psycopg is not installed")
            self.connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        else:
            self.connection = sqlite3.connect(DATABASE)
            self.connection.row_factory = sqlite3.Row

    def execute(self, query, parameters=()):
        if not self.is_postgres:
            query = query.replace("%s", "?")
        return self.connection.execute(query, parameters)

    def executemany(self, query, parameters):
        if not self.is_postgres:
            query = query.replace("%s", "?")
        return self.connection.executemany(query, parameters)

    def commit(self):
        self.connection.commit()

    def close(self):
        self.connection.close()


@app.teardown_appcontext
def close_db(_error=None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    db = get_db()
    id_definition = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if db.is_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"
    schema = """
        CREATE TABLE IF NOT EXISTS members (
            id {id_definition},
            name TEXT NOT NULL,
            number TEXT NOT NULL,
            position TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS practices (
            id {id_definition},
            practice_date TEXT NOT NULL,
            start_time TEXT NOT NULL,
            location TEXT NOT NULL,
            is_cancelled INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS attendance (
            id {id_definition},
            member_id INTEGER NOT NULL,
            practice_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'present',
            UNIQUE(member_id, practice_id),
            FOREIGN KEY(member_id) REFERENCES members(id),
            FOREIGN KEY(practice_id) REFERENCES practices(id)
        );
        CREATE TABLE IF NOT EXISTS games (
            id {id_definition},
            game_date TEXT NOT NULL,
            opponent TEXT NOT NULL,
            location TEXT NOT NULL,
            result TEXT NOT NULL DEFAULT ''
        );
        CREATE TABLE IF NOT EXISTS game_stats (
            id {id_definition},
            game_id INTEGER NOT NULL,
            member_id INTEGER NOT NULL,
            points INTEGER NOT NULL DEFAULT 0,
            rebounds INTEGER NOT NULL DEFAULT 0,
            assists INTEGER NOT NULL DEFAULT 0,
            steals INTEGER NOT NULL DEFAULT 0,
            blocks INTEGER NOT NULL DEFAULT 0,
            fouls INTEGER NOT NULL DEFAULT 0,
            turnovers INTEGER NOT NULL DEFAULT 0,
            two_pm INTEGER NOT NULL DEFAULT 0,
            two_pa INTEGER NOT NULL DEFAULT 0,
            three_pm INTEGER NOT NULL DEFAULT 0,
            three_pa INTEGER NOT NULL DEFAULT 0,
            free_throw_m INTEGER NOT NULL DEFAULT 0,
            free_throw_a INTEGER NOT NULL DEFAULT 0,
            UNIQUE(game_id, member_id),
            FOREIGN KEY(game_id) REFERENCES games(id),
            FOREIGN KEY(member_id) REFERENCES members(id)
        );
        CREATE TABLE IF NOT EXISTS opponent_players (
            id {id_definition},
            game_id INTEGER NOT NULL,
            number TEXT NOT NULL,
            UNIQUE(game_id, number),
            FOREIGN KEY(game_id) REFERENCES games(id)
        );
        CREATE TABLE IF NOT EXISTS opponent_stats (
            id {id_definition},
            game_id INTEGER NOT NULL,
            opponent_player_id INTEGER NOT NULL,
            two_pm INTEGER NOT NULL DEFAULT 0,
            two_pa INTEGER NOT NULL DEFAULT 0,
            three_pm INTEGER NOT NULL DEFAULT 0,
            three_pa INTEGER NOT NULL DEFAULT 0,
            free_throw_m INTEGER NOT NULL DEFAULT 0,
            free_throw_a INTEGER NOT NULL DEFAULT 0,
            rebounds INTEGER NOT NULL DEFAULT 0,
            turnovers INTEGER NOT NULL DEFAULT 0,
            assists INTEGER NOT NULL DEFAULT 0,
            fouls INTEGER NOT NULL DEFAULT 0,
            UNIQUE(game_id, opponent_player_id),
            FOREIGN KEY(game_id) REFERENCES games(id),
            FOREIGN KEY(opponent_player_id) REFERENCES opponent_players(id)
        );
        CREATE TABLE IF NOT EXISTS events (
            id {id_definition},
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            start_time TEXT NOT NULL,
            end_time TEXT NOT NULL,
            title TEXT NOT NULL,
            location TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS dashboard_memos (
            id INTEGER PRIMARY KEY,
            content TEXT NOT NULL DEFAULT ''
        );
        CREATE TABLE IF NOT EXISTS game_participation (
            id {id_definition},
            game_id INTEGER NOT NULL,
            member_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            UNIQUE(game_id, member_id),
            FOREIGN KEY(game_id) REFERENCES games(id),
            FOREIGN KEY(member_id) REFERENCES members(id)
        );
        """.format(id_definition=id_definition)
    if db.is_postgres:
        for statement in schema.split(";"):
            if statement.strip():
                db.execute(statement)
    else:
        db.connection.executescript(schema)
        columns = {row[1] for row in db.execute("PRAGMA table_info(practices)").fetchall()}
        if "is_cancelled" not in columns:
            db.execute("ALTER TABLE practices ADD COLUMN is_cancelled INTEGER NOT NULL DEFAULT 0")
        stat_columns = {row[1] for row in db.execute("PRAGMA table_info(game_stats)").fetchall()}
        for column in ("two_pm", "two_pa", "three_pm", "three_pa", "free_throw_m", "free_throw_a"):
            if column not in stat_columns:
                db.execute(f"ALTER TABLE game_stats ADD COLUMN {column} INTEGER NOT NULL DEFAULT 0")
    if db.execute("SELECT COUNT(*) AS count FROM members").fetchone()["count"] == 0:
        db.executemany(
            "INSERT INTO members (name, number, position) VALUES (%s, %s, %s)",
            [("山田 太郎", "#4", "G"), ("佐藤 花子", "#7", "F"), ("鈴木 一郎", "#10", "G"), ("高橋 翼", "#12", "C"), ("伊藤 美咲", "#15", "F")],
        )
    if db.execute("SELECT COUNT(*) AS count FROM practices").fetchone()["count"] == 0:
        today = date.today()
        db.executemany(
            "INSERT INTO practices (practice_date, start_time, location) VALUES (%s, %s, %s)",
            [((today - timedelta(days=offset)).isoformat(), time, "第一体育館") for offset, time in [(0, "18:30"), (1, "18:30"), (3, "19:00"), (5, "18:30"), (7, "19:00")]],
        )
    db.commit()


def practice_rule(day):
    if day.weekday() == 1:
        return "17:00", "19:00"
    if day.weekday() == 3:
        return "18:00", "20:00"
    if day.weekday() == 5 and ((day.day - 1) // 7 + 1) in (2, 4, 5):
        return "17:00", "20:00"
    if day.weekday() == 6:
        return "10:00", "13:00"
    return None


def ensure_month_practices(year, month):
    db = get_db()
    last_day = calendar.monthrange(year, month)[1]
    for day_number in range(1, last_day + 1):
        practice_day = date(year, month, day_number)
        rule = practice_rule(practice_day)
        if rule is None:
            continue
        exists = db.execute("SELECT id FROM practices WHERE practice_date = %s", (practice_day.isoformat(),)).fetchone()
        if exists is None:
            db.execute("INSERT INTO practices (practice_date, start_time, location) VALUES (%s, %s, %s)", (practice_day.isoformat(), f"{rule[0]} - {rule[1]}", "第一体育館"))
        else:
            current = db.execute("SELECT start_time FROM practices WHERE id = %s", (exists["id"],)).fetchone()
            if " - " not in current["start_time"]:
                db.execute("UPDATE practices SET start_time = %s WHERE id = %s", (f"{rule[0]} - {rule[1]}", exists["id"]))
    db.commit()


@app.before_request
def load_user_and_database():
    init_db()


@app.route("/", methods=("GET", "POST"))
def dashboard():
    db = get_db()
    if request.method == "POST":
        if request.form.get("action") == "memo":
            content = request.form.get("content", "").strip()
            db.execute("INSERT INTO dashboard_memos (id, content) VALUES (1, %s) ON CONFLICT(id) DO UPDATE SET content = EXCLUDED.content", (content,))
            db.commit()
            flash("連絡メモを更新しました。", "success")
            return redirect(url_for("dashboard", selected=request.form.get("selected", ""), month=request.form.get("month", "")))
        member_id = request.form.get("member_id", type=int)
        practice_id = request.form.get("practice_id", type=int)
        if member_id and practice_id:
            practice_status = db.execute("SELECT is_cancelled FROM practices WHERE id = %s", (practice_id,)).fetchone()
            if practice_status and practice_status["is_cancelled"]:
                flash("休止中の練習には出席を登録できません。", "error")
                return redirect(url_for("dashboard", selected=request.form.get("selected", ""), month=request.form.get("month", "")))
            db.execute("""INSERT INTO attendance (member_id, practice_id, status)
                VALUES (%s, %s, 'present')
                ON CONFLICT(member_id, practice_id)
                DO UPDATE SET status = EXCLUDED.status""", (member_id, practice_id))
            db.commit()
            flash("出席を登録しました。", "success")
        return redirect(url_for("dashboard", selected=request.form.get("selected", ""), month=request.form.get("month", "")))

    today = date.today()
    try:
        month_date = datetime.strptime(request.args.get("month", today.strftime("%Y-%m")), "%Y-%m").date().replace(day=1)
    except ValueError:
        month_date = today.replace(day=1)
    ensure_month_practices(month_date.year, month_date.month)
    practices = db.execute("SELECT * FROM practices WHERE practice_date LIKE %s ORDER BY practice_date", (f"{month_date:%Y-%m}%",)).fetchall()
    events = db.execute("SELECT * FROM events WHERE start_date <= %s AND end_date >= %s ORDER BY start_date, start_time", (f"{month_date:%Y-%m}-31", f"{month_date:%Y-%m}-01")).fetchall()
    selected = request.args.get("selected") or (today.isoformat() if any(item["practice_date"] == today.isoformat() for item in practices) else (practices[0]["practice_date"] if practices else ""))
    practice = next((item for item in practices if item["practice_date"] == selected), None)
    members = db.execute(
        """
        SELECT m.*, a.status FROM members m
        LEFT JOIN attendance a ON a.member_id = m.id AND a.practice_id = %s
        ORDER BY CAST(REPLACE(m.number, '#', '') AS INTEGER)
        """,
        (practice["id"],) if practice else (0,),
    ).fetchall()
    present_count = sum(member["status"] == "present" for member in members) if practice else 0
    previous_month = (month_date - timedelta(days=1)).replace(day=1)
    next_month = (month_date + timedelta(days=32)).replace(day=1)
    calendar_days = calendar.Calendar(firstweekday=6).monthdatescalendar(month_date.year, month_date.month)
    practice_by_date = {item["practice_date"]: item for item in practices}
    events_by_date = {}
    for event in events:
        event_day = datetime.strptime(event["start_date"], "%Y-%m-%d").date()
        event_end = datetime.strptime(event["end_date"], "%Y-%m-%d").date()
        while event_day <= event_end:
            if event_day.strftime("%Y-%m") == month_date.strftime("%Y-%m"):
                events_by_date.setdefault(event_day.isoformat(), []).append(event)
            event_day += timedelta(days=1)
    memo_row = db.execute("SELECT content FROM dashboard_memos WHERE id = 1").fetchone()
    memo = memo_row["content"] if memo_row else ""
    selected_events = events_by_date.get(selected, [])
    return render_template("dashboard.html", practices=practices, practice=practice, selected=selected, members=members, present_count=present_count, calendar_days=calendar_days, practice_by_date=practice_by_date, events_by_date=events_by_date, selected_events=selected_events, memo=memo, month_date=month_date, previous_month=previous_month, next_month=next_month)


@app.route("/practices/<int:practice_id>/toggle", methods=("POST",))
def toggle_practice(practice_id):
    db = get_db()
    db.execute("UPDATE practices SET is_cancelled = CASE WHEN is_cancelled <> 0 THEN 0 ELSE 1 END WHERE id = %s", (practice_id,))
    db.commit()
    flash("練習予定を更新しました。", "success")
    return redirect(url_for("dashboard", selected=request.form.get("selected", ""), month=request.form.get("month", "")))


@app.route("/practices/<int:practice_id>/delete", methods=("POST",))
def delete_practice(practice_id):
    db = get_db()
    db.execute("DELETE FROM attendance WHERE practice_id = %s", (practice_id,))
    db.execute("DELETE FROM practices WHERE id = %s", (practice_id,))
    db.commit()
    flash("練習予定を削除しました。", "success")
    return redirect(url_for("dashboard", month=request.form.get("month", "")))


@app.route("/events/<int:event_id>/delete", methods=("POST",))
def delete_event(event_id):
    db = get_db()
    db.execute("DELETE FROM events WHERE id = %s", (event_id,))
    db.commit()
    flash("イベント予定を削除しました。", "success")
    return redirect(url_for("dashboard", selected=request.form.get("selected", ""), month=request.form.get("month", "")))


@app.route("/practices/new", methods=("GET", "POST"))
def add_practice():
    if request.method == "POST":
        start_date = request.form.get("start_date", "")
        end_date = request.form.get("end_date", "") or start_date
        start_time = request.form.get("start_time", "").strip()
        end_time = request.form.get("end_time", "").strip()
        title = request.form.get("title", "").strip()
        location = request.form.get("location", "第一体育館").strip()
        try:
            datetime.strptime(start_date, "%Y-%m-%d")
            datetime.strptime(end_date, "%Y-%m-%d")
            if end_date < start_date or not start_time or not end_time or not title or not location:
                raise ValueError
            if title == "練習" and start_date != end_date:
                flash("練習は開始日と終了日を同じ日にしてください。", "error")
                return render_template("add_practice.html")
        except ValueError:
            flash("日付、時間、内容、場所を正しく入力してください。", "error")
        else:
            db = get_db()
            if title != "練習":
                db.execute("INSERT INTO events (start_date, end_date, start_time, end_time, title, location) VALUES (%s, %s, %s, %s, %s, %s)", (start_date, end_date, start_time, end_time, title, location))
                db.commit()
                flash("イベント予定を追加しました。", "success")
                return redirect(url_for("dashboard", selected=start_date, month=start_date[:7]))
            existing = db.execute("SELECT id FROM practices WHERE practice_date = %s", (start_date,)).fetchone()
            if existing:
                db.execute("UPDATE practices SET start_time = %s, location = %s, is_cancelled = 0 WHERE id = %s", (f"{start_time} - {end_time}", location, existing["id"]))
            else:
                db.execute("INSERT INTO practices (practice_date, start_time, location) VALUES (%s, %s, %s)", (start_date, f"{start_time} - {end_time}", location))
            db.commit()
            flash("練習予定を追加しました。", "success")
            return redirect(url_for("dashboard", selected=start_date, month=start_date[:7]))
    return render_template("add_practice.html")


@app.route("/members/<int:member_id>/edit", methods=("GET", "POST"))
def edit_member(member_id):
    db = get_db()
    member = db.execute("SELECT * FROM members WHERE id = %s", (member_id,)).fetchone()
    if member is None:
        return "メンバーが見つかりません", 404
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        number = request.form.get("number", "").strip()
        if not name or not number:
            flash("名前と背番号を入力してください。", "error")
        else:
            db.execute("UPDATE members SET name = %s, number = %s WHERE id = %s", (name, number, member_id))
            db.commit()
            flash("名前を更新しました。", "success")
            return redirect(url_for("dashboard"))
    return render_template("edit_member.html", member=member)


@app.route("/members/new", methods=("GET", "POST"))
def add_member():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        number = request.form.get("number", "").strip()
        position = request.form.get("position", "").strip().upper()
        if not name or not number:
            flash("名前と背番号を入力してください。", "error")
        else:
            db = get_db()
            db.execute("INSERT INTO members (name, number, position) VALUES (%s, %s, %s)", (name, number, position))
            db.commit()
            flash("メンバーを追加しました。", "success")
            return redirect(url_for("dashboard"))
    return render_template("add_member.html")


@app.route("/stats", methods=("GET", "POST"))
def stats():
    db = get_db()
    if request.method == "POST":
        game_id = request.form.get("game_id", type=int)
        side = request.form.get("side", "team")
        if request.form.get("action") == "participation":
            member_id = request.form.get("member_id", type=int)
            status = request.form.get("status", "pending")
            if member_id and status in ("yes", "no", "pending"):
                db.execute("""INSERT INTO game_participation (game_id, member_id, status)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(game_id, member_id)
                    DO UPDATE SET status = EXCLUDED.status""", (game_id, member_id, status))
                db.commit()
                flash("試合参加アンケートを更新しました。", "success")
            return redirect(url_for("stats", game=game_id, side="participation"))
        player_rows = db.execute("SELECT id FROM opponent_players WHERE game_id = %s" if side == "opponent" else "SELECT id FROM members", (game_id,) if side == "opponent" else ()).fetchall()
        metrics = ("two_pm", "two_pa", "three_pm", "three_pa", "free_throw_m", "free_throw_a", "rebounds", "turnovers", "assists", "fouls")
        table = "opponent_stats" if side == "opponent" else "game_stats"
        key = "opponent_player_id" if side == "opponent" else "member_id"
        for player in player_rows:
            values = [max(0, request.form.get(f"{metric}_{player['id']}", 0, type=int) or 0) for metric in metrics]
            db.execute(f"""INSERT INTO {table} (game_id, {key}, two_pm, two_pa, three_pm, three_pa, free_throw_m, free_throw_a, rebounds, turnovers, assists, fouls)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT(game_id, {key}) DO UPDATE SET two_pm=EXCLUDED.two_pm, two_pa=EXCLUDED.two_pa,
                three_pm=EXCLUDED.three_pm, three_pa=EXCLUDED.three_pa, free_throw_m=EXCLUDED.free_throw_m,
                free_throw_a=EXCLUDED.free_throw_a, rebounds=EXCLUDED.rebounds, turnovers=EXCLUDED.turnovers,
                assists=EXCLUDED.assists, fouls=EXCLUDED.fouls""", (game_id, player["id"], *values))
        db.commit()
        flash("スタッツを保存しました。", "success")
        return redirect(url_for("stats", game=game_id))

    games = db.execute("SELECT * FROM games ORDER BY game_date DESC, id DESC").fetchall()
    game = next((item for item in games if str(item["id"]) == request.args.get("game")), games[0] if games else None)
    members = []
    opponents = []
    totals = {metric: 0 for metric in ("points", "two_pm", "two_pa", "three_pm", "three_pa", "free_throw_m", "free_throw_a", "rebounds", "turnovers", "assists", "fouls")}
    if game:
        participation = db.execute("""SELECT m.id, m.name, m.number, COALESCE(p.status, 'pending') status
            FROM members m LEFT JOIN game_participation p ON p.member_id = m.id AND p.game_id = %s
            ORDER BY CAST(REPLACE(m.number, '#', '') AS INTEGER)""", (game["id"],)).fetchall()
        members = db.execute(
            """SELECT m.*, COALESCE(s.two_pm, 0) two_pm, COALESCE(s.two_pa, 0) two_pa,
            COALESCE(s.three_pm, 0) three_pm, COALESCE(s.three_pa, 0) three_pa,
            COALESCE(s.free_throw_m, 0) free_throw_m, COALESCE(s.free_throw_a, 0) free_throw_a,
            COALESCE(s.rebounds, 0) rebounds, COALESCE(s.turnovers, 0) turnovers,
            COALESCE(s.assists, 0) assists, COALESCE(s.fouls, 0) fouls,
            (COALESCE(s.two_pm, 0) * 2 + COALESCE(s.three_pm, 0) * 3 + COALESCE(s.free_throw_m, 0)) points
            FROM members m
            LEFT JOIN game_stats s ON s.member_id = m.id AND s.game_id = %s
            ORDER BY CAST(REPLACE(m.number, '#', '') AS INTEGER)""",
            (game["id"],),
        ).fetchall()
        for member in members:
            for metric in totals:
                totals[metric] += member[metric]
        opponents = db.execute("""SELECT p.*, COALESCE(s.two_pm, 0) two_pm, COALESCE(s.two_pa, 0) two_pa,
            COALESCE(s.three_pm, 0) three_pm, COALESCE(s.three_pa, 0) three_pa,
            COALESCE(s.free_throw_m, 0) free_throw_m, COALESCE(s.free_throw_a, 0) free_throw_a,
            COALESCE(s.rebounds, 0) rebounds, COALESCE(s.turnovers, 0) turnovers,
            COALESCE(s.assists, 0) assists, COALESCE(s.fouls, 0) fouls,
            (COALESCE(s.two_pm, 0) * 2 + COALESCE(s.three_pm, 0) * 3 + COALESCE(s.free_throw_m, 0)) points
            FROM opponent_players p LEFT JOIN opponent_stats s ON s.opponent_player_id = p.id AND s.game_id = %s
            WHERE p.game_id = %s ORDER BY CAST(REPLACE(p.number, '#', '') AS INTEGER)""", (game["id"], game["id"])).fetchall()
    opponent_totals = {metric: 0 for metric in totals}
    for player in opponents:
        for metric in opponent_totals:
            opponent_totals[metric] += player[metric]
    participation = participation if game else []
    return render_template("stats.html", games=games, game=game, members=members, opponents=opponents, participation=participation, totals=totals, opponent_totals=opponent_totals, side=request.args.get("side", "team"))


@app.route("/stats/<int:game_id>/opponents/new", methods=("POST",))
def add_opponent(game_id):
    number = request.form.get("number", "").strip()
    if not number:
        flash("相手選手の番号を入力してください。", "error")
    else:
        db = get_db()
        db.execute("INSERT INTO opponent_players (game_id, number) VALUES (%s, %s) ON CONFLICT(game_id, number) DO NOTHING", (game_id, number))
        db.commit()
        flash("相手選手を追加しました。", "success")
    return redirect(url_for("stats", game=game_id, side="opponent"))


@app.route("/participation", methods=("GET", "POST"))
def participation():
    db = get_db()
    games = db.execute("SELECT * FROM games ORDER BY game_date DESC, id DESC").fetchall()
    game = next((item for item in games if str(item["id"]) == request.args.get("game")), games[0] if games else None)
    if request.method == "POST" and game:
        member_id = request.form.get("member_id", type=int)
        status = request.form.get("status", "pending")
        if member_id and status in ("yes", "no", "pending"):
            db.execute("""INSERT INTO game_participation (game_id, member_id, status)
                VALUES (%s, %s, %s)
                ON CONFLICT(game_id, member_id)
                DO UPDATE SET status = EXCLUDED.status""", (game["id"], member_id, status))
            db.commit()
            flash("参加アンケートを更新しました。", "success")
        return redirect(url_for("participation", game=game["id"]))
    responses = db.execute("""SELECT m.id, m.name, m.number, COALESCE(p.status, 'pending') status
        FROM members m LEFT JOIN game_participation p ON p.member_id = m.id AND p.game_id = %s
        ORDER BY CAST(REPLACE(m.number, '#', '') AS INTEGER)""", (game["id"],)).fetchall() if game else []
    return render_template("participation.html", games=games, game=game, responses=responses)


@app.route("/stats/games/new", methods=("GET", "POST"))
def add_game():
    if request.method == "POST":
        game_date = request.form.get("game_date", "")
        opponent = request.form.get("opponent", "").strip()
        location = request.form.get("location", "").strip()
        if not game_date or not opponent or not location:
            flash("試合日、対戦相手、会場を入力してください。", "error")
        else:
            db = get_db()
            cursor = db.execute("INSERT INTO games (game_date, opponent, location) VALUES (%s, %s, %s) RETURNING id", (game_date, opponent, location))
            game_id = cursor.fetchone()["id"]
            db.commit()
            return redirect(url_for("stats", game=game_id))
    return render_template("add_game.html")


if __name__ == "__main__":
    with app.app_context():
        init_db()
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", "5000")), debug=True)
